name: Preview

on:
  push:
    branches-ignore:
      - main

jobs:
  format-test-lint:
    uses: Byont-Ventures/web3-template/.github/workflows/format-test-lint.yml@1-add-basic-website-components
    secrets: inherit

  deploy:
    uses: Byont-Ventures/web3-template/.github/workflows/vercel.yml@1-add-basic-website-components
    with:
      VERCEL_ENVIRONMENT: preview
    secrets: inherit
